import Theme from "./styles/theme";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Theme>
        <body className="tw-bg-shaft">{children}</body>
      </Theme>
    </html>
  );
}
